### ISSUE TITLE
vm.rs:1167:13

### ISSUE THREAD

**Issue by JONEmoad** [fuzzland/ityfuzz#36]
I am encountering this issue with 90% of the results I have run on the Docker image

[Testcase #0] run time: 0h-1m-5s, clients: 1, corpus: 58, objectives: 0, executions: 893, exec/sec: 16
thread 'main' panicked at 'no code 0x10ed43c718714eb63d5aa57b78b54704e256024e', /build/src/evm/vm.rs:1167:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/core/src/option.rs:1880:5
   5: <ityfuzz::evm::vm::EVMExecutor<I,S,VS> as ityfuzz::generic_vm::vm_executor::GenericVM<VS,revm::interpreter::bytecode::Bytecode,bytes::bytes::Bytes,primitive_types::H160,primitive_types::H160,primitive_types::U256,alloc::vec::Vec<u8>,I,S>>::execute
   6: <ityfuzz::executor::FuzzExecutor<VS,Addr,Code,By,Loc,SlotTy,Out,I,S,OT> as libafl::executors::Executor<EM,I,S,Z>>::run_target
   7: <(Head,Tail) as libafl::stages::StagesTuple<E,EM,S,Z>>::perform_all
   8: <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,I,OF,S,OT> as libafl::fuzzer::Fuzzer<E,EM,I,S,ST>>::fuzz_loop
   9: ityfuzz::fuzzers::cmp_fuzzer::cmp_fuzzer
  10: cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by shouc** [comment]
you need to add 0x10ed43c718714eb63d5aa57b78b54704e256024e (pancakeswap router) in the targets.

**Comment by shouc** [comment]
In tomorrow's release, this will be handled more elegantly.
