### ISSUE TITLE
Integer overflow when casting to usize.

### ISSUE THREAD

**Issue by 0xxfu** [fuzzland/ityfuzz#364]
Command:
```
export ETH_RPC_URL=https://goerli.base.org
RUST_BACKTRACE=full ityfuzz evm\
 -t 0xbfb30dc22dd4d4c7b829fd84abf55f85ae311828\
 -o -i -f -p\
 --onchain-block-number 12539781\
 --onchain-url https://goerli.base.org\
 --onchain-chain-id 84531\
 --onchain-explorer-url https://goerli.basescan.org\
 --onchain-chain-name BASE_GOERLI\
 --onchain-etherscan-api-key ${privateKey}
```

Print:
```
 ================ EVM Fuzzer Start ===================


 INFO Deploying contract: 0xbfb30dc22dd4d4c7b829fd84abf55f85ae311828
 INFO Contract 0xbfb30dc22dd4d4c7b829fd84abf55f85ae311828 deployed to: 0xbfb30dc22dd4d4c7b829fd84abf55f85ae311828
 INFO Deployed all contracts

info: ⠙ executing '0xd120d1a8'                                                                                               thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/primitive-types-0.12.2/src/lib.rs:38:1:
Integer overflow when casting to usize
stack backtrace:
   0:        0x105f8539c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdcf5a8f170d2fa38
   1:        0x105fa540c - core::fmt::write::h43a20d1d43ba2c4c
   2:        0x105f82434 - std::io::Write::write_fmt::hc8f02cc7d187633a
   3:        0x105f851d8 - std::sys_common::backtrace::print::h0f98126c99b558bc
   4:        0x105f86afc - std::panicking::default_hook::{{closure}}::h37ce2903b5a4a707
   5:        0x105f86844 - std::panicking::default_hook::hdce48845581ed2b0
   6:        0x105f8705c - std::panicking::rust_panic_with_hook::h130fbf332c6cdd6d
   7:        0x105f86e00 - std::panicking::begin_panic_handler::{{closure}}::hace05675132c4b37
   8:        0x105f85804 - std::sys_common::backtrace::__rust_end_short_backtrace::hb5df50aeda7bb9d6
   9:        0x105f86bc0 - _rust_begin_unwind
  10:        0x105ffe900 - core::panicking::panic_fmt::h9d18abbacad43fc7
  11:        0x104ddff50 - <primitive_types::U256 as core::ops::bit::Shl<T>>::shl::h0dcd3c6c57b85c5e
  12:        0x104dd7d5c - heimdall_common::ether::evm::core::vm::VM::_step::h97cc86ea37d5fbd2
  13:        0x104ddb9cc - heimdall_common::ether::evm::core::vm::VM::step::h8a842a6af77a0652
  14:        0x104ddc280 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  15:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  16:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  17:        0x104ddd6d4 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  18:        0x104ddd5b0 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  19:        0x104ddd5b0 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  20:        0x104ddd6d4 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  21:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  22:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  23:        0x104ddd5b0 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  24:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  25:        0x104ddd5b0 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  26:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  27:        0x104ddd5b0 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  28:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  29:        0x104ddd5b0 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  30:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  31:        0x104ddd5b0 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  32:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  33:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  34:        0x104ddd5b0 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  35:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  36:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  37:        0x104ddd5b0 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  38:        0x104ddd6d4 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  39:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  40:        0x104ddd5b0 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  41:        0x104ddd5b0 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  42:        0x104ddd664 - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::recursive_map::h12999f8534837390
  43:        0x104ddc06c - heimdall_common::ether::evm::ext::exec::<impl heimdall_common::ether::evm::core::vm::VM>::symbolic_exec_selector::h0953f71d111e27d5
  44:        0x104c3a27c - heimdall_core::decompile::decompile::{{closure}}::h331f6f3e4c174113
  45:        0x104c516b8 - tokio::runtime::scheduler::current_thread::Context::enter::hc295a19e47cf815b
  46:        0x104c12b64 - tokio::runtime::context::scoped::Scoped<T>::set::h2d73fa3283dccfe8
  47:        0x104c51a8c - tokio::runtime::scheduler::current_thread::CoreGuard::block_on::h4da066a2f2d8bd69
  48:        0x104c12eec - tokio::runtime::context::runtime::enter_runtime::h1cc6925746def241
  49:        0x104c1315c - tokio::runtime::runtime::Runtime::block_on::ha6590a725e700039
  50:        0x104a6b6e8 - ityfuzz::evm::onchain::abi_decompiler::fetch_abi_heimdall::h2ffe262b9d156c9d
  51:        0x104ae39a4 - ityfuzz::evm::corpus_initializer::EVMCorpusInitializer<SC,ISC>::initialize_corpus::he71212e8ffe0e878
  52:        0x104ae2568 - ityfuzz::evm::corpus_initializer::EVMCorpusInitializer<SC,ISC>::initialize::h7eb886cb5f3a249a
  53:        0x104c68210 - ityfuzz::fuzzers::evm_fuzzer::evm_fuzzer::hd4f4447089792720
  54:        0x104c2332c - ityfuzz::evm::evm_main::h1237508dee5fb77c
  55:        0x104acfc90 - ityfuzz::main::h9b6e035e457fa007
  56:        0x104bff8e8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h12c2fff17dffdd36
  57:        0x104b2e0c0 - std::rt::lang_start::{{closure}}::he6aa290337ebd73f
  58:        0x105f7bd5c - std::rt::lang_start_internal::hb81d8036ff3fc9c3
  59:        0x104b2e0a4 - std::rt::lang_start::h4bc7fc1d757e5f18
  60:        0x104ad107c - _main
```

It looks like an error from [decompiler](https://github.com/Jon-Becker/heimdall-rs).

**Comment by 0xAWM** [comment]
use:
```
--onchain-explorer-url https://api-goerli.basescan.org/api
```

**Comment by 0xxfu** [comment]
Thank you. The overflow error is resolved with `--onchain-explorer-url https://api-goerli.basescan.org/api`.

Another error was thrown:

```
thread 'main' panicked at src/evm/onchain/endpoints.rs:931:18:
[Flashloan] Network is not supported
stack backtrace:
   0:        0x1063d939c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdcf5a8f170d2fa38
   1:        0x1063f940c - core::fmt::write::h43a20d1d43ba2c4c
   2:        0x1063d6434 - std::io::Write::write_fmt::hc8f02cc7d187633a
   3:        0x1063d91d8 - std::sys_common::backtrace::print::h0f98126c99b558bc
   4:        0x1063daafc - std::panicking::default_hook::{{closure}}::h37ce2903b5a4a707
   5:        0x1063da844 - std::panicking::default_hook::hdce48845581ed2b0
   6:        0x1063db05c - std::panicking::rust_panic_with_hook::h130fbf332c6cdd6d
   7:        0x1063dae00 - std::panicking::begin_panic_handler::{{closure}}::hace05675132c4b37
   8:        0x1063d9804 - std::sys_common::backtrace::__rust_end_short_backtrace::hb5df50aeda7bb9d6
   9:        0x1063dabc0 - _rust_begin_unwind
  10:        0x106452900 - core::panicking::panic_fmt::h9d18abbacad43fc7
  11:        0x10507188c - ityfuzz::evm::onchain::endpoints::OnChainConfig::get_pegged_token::h6763324002ac430c
  12:        0x10506f74c - ityfuzz::evm::onchain::endpoints::OnChainConfig::fetch_uniswap_path_cached::h414e5bb8920cdd7c
  13:        0x104de78a0 - ityfuzz::evm::onchain::flashloan::Flashloan<VS,I,S>::on_contract_insertion::haa3a90563acfc9c8
  14:        0x104f67650 - ityfuzz::evm::onchain::OnChain<VS,I,S>::load_code::hf769bd053e7ec114
  15:        0x104f64f94 - <ityfuzz::evm::onchain::OnChain<VS,I,S> as ityfuzz::evm::middlewares::middleware::Middleware<VS,I,S,SC>>::on_step::hd2da927918264312
  16:        0x104f58058 - <ityfuzz::evm::host::FuzzHost<VS,I,S,SC> as revm_interpreter::host::Host<S>>::step::h397e75d6ade62a1c
  17:        0x104f27fe0 - revm_interpreter::interpreter::Interpreter::run_inspect::h2fff78b392b5c121
  18:        0x104f6c288 - ityfuzz::evm::vm::EVMExecutor<I,S,VS,CI,SC>::execute_from_pc::h4320becab9ecc253
  19:        0x104f6d30c - ityfuzz::evm::vm::EVMExecutor<I,S,VS,CI,SC>::execute_abi::h4a6a46dfabb6b06e
  20:        0x1050b966c - <ityfuzz::executor::FuzzExecutor<VS,Addr,Code,By,Loc,SlotTy,Out,I,S,OT,CI> as libafl::executors::Executor<EM,Z>>::run_target::hd4bfa740e8a35551
  21:        0x105019ab0 - <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,IFR,I,OF,S,OT,CI,SM> as libafl::fuzzer::Evaluator<E,EM>>::evaluate_input_events::h5504b65f43763120
  22:        0x105093cb4 - <(Head,Tail) as libafl::stages::StagesTuple<E,EM,<Head as libafl::state::UsesState>::State,Z>>::perform_all::h10c3655599e66244
  23:        0x105019460 - <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,IFR,I,OF,S,OT,CI,SM> as libafl::fuzzer::Fuzzer<E,EM,ST>>::fuzz_loop::hcf4e3027743a2ac7
  24:        0x1050c1ec4 - ityfuzz::fuzzers::evm_fuzzer::evm_fuzzer::hd4f4447089792720
  25:        0x10507732c - ityfuzz::evm::evm_main::h1237508dee5fb77c
  26:        0x104f23c90 - ityfuzz::main::h9b6e035e457fa007
  27:        0x1050538e8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h12c2fff17dffdd36
  28:        0x104f820c0 - std::rt::lang_start::{{closure}}::he6aa290337ebd73f
  29:        0x1063cfd5c - std::rt::lang_start_internal::hb81d8036ff3fc9c3
  30:        0x104f820a4 - std::rt::lang_start::h4bc7fc1d757e5f18
  31:        0x104f2507c - _main
```

**Comment by 0xAWM** [comment]
As shown in console: [Flashloan] Network is not supported.

Ityfuzz Flashloan on base chain is not supported for the time being. The underlying reason is that we have not adapted its dex.

**Comment by 0xAWM** [comment]
We will skip parsing pair in this case to avoid panic.

**Comment by 0xxfu** [comment]
https://github.com/fuzzland/ityfuzz/blob/7fba3fe4b02d62f3eebd80b3234a0fc9b401b38b/src/evm/onchain/endpoints.rs#L862-L905

https://github.com/fuzzland/ityfuzz/blob/7fba3fe4b02d62f3eebd80b3234a0fc9b401b38b/src/evm/onchain/endpoints.rs#L810-L815

Can we provide pegged token and pair URL by inputting command parameters?

For example:
```
--pegged-token 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2,0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48 \
--pairs-url https://pairs.infra.fuzz.land/pairs
```

**Comment by shouc** [comment]
Yes, manually defining LPs and constant price tokens will be supported soon. The issue with using factory is that a lot of liquidation paths involve multiple tokens and pairs. For instance, if I want to sell a shitcoin, there is shitcoin-usdt pair and shicoin-shitcoin' pair. A lot of vulnerabilities occur actually because of shicoin-shitcoin' pair.
