### ISSUE TITLE
failed to deploy contract: thread 'main' panicked at src/evm/contract_utils.rs:786:9

### ISSUE THREAD

**Issue by 0xxfu** [fuzzland/ityfuzz#373]
# Issue Reproduction

1. install the Blazo: https://github.com/fuzzland/blazo/tree/main
2. clone and init the demo repo: https://github.com/0xxfu/template-ethereum-contracts
3. generate `results.json`:
```
blazo .
```
4. 
```
RUST_BACKTRACE=full ityfuzz evm --builder-artifacts-file ./results.json -t "a" --work-dir ./.ityfuzz --setup-file src/ERC20/SimpleERC20.sol:SimpleERC20
```

Results:
```
ERROR deploy failed: Revert
thread 'main' panicked at src/evm/contract_utils.rs:786:9:
failed to deploy contract
stack backtrace:
   0:        0x104145304 - std::backtrace_rs::backtrace::libunwind::trace::hd2c3bc335a80d49d
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:        0x104145304 - std::backtrace_rs::backtrace::trace_unsynchronized::h3e552ef46bc77e4b
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x104145304 - std::sys_common::backtrace::_print_fmt::h99597d36a7215aa5
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x104145304 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hdcf5a8f170d2fa38
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x104165374 - core::fmt::rt::Argument::fmt::he7ca4a6208f6679a
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/fmt/rt.rs:142:9
   5:        0x104165374 - core::fmt::write::h43a20d1d43ba2c4c
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/fmt/mod.rs:1117:17
   6:        0x10414239c - std::io::Write::write_fmt::hc8f02cc7d187633a
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/io/mod.rs:1763:15
   7:        0x104145140 - std::sys_common::backtrace::_print::h1e64118eeca02da5
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x104145140 - std::sys_common::backtrace::print::h0f98126c99b558bc
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x104146a64 - std::panicking::default_hook::{{closure}}::h37ce2903b5a4a707
  10:        0x1041467ac - std::panicking::default_hook::hdce48845581ed2b0
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:292:9
  11:        0x104146fc4 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h075e1f0fd4e5fba9
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/alloc/src/boxed.rs:2021:9
  12:        0x104146fc4 - std::panicking::rust_panic_with_hook::h130fbf332c6cdd6d
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:783:13
  13:        0x104146d68 - std::panicking::begin_panic_handler::{{closure}}::hace05675132c4b37
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:649:13
  14:        0x10414576c - std::sys_common::backtrace::__rust_end_short_backtrace::hb5df50aeda7bb9d6
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/sys_common/backtrace.rs:170:18
  15:        0x104146b28 - rust_begin_unwind
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:645:5
  16:        0x1041bfc88 - core::panicking::panic_fmt::h9d18abbacad43fc7
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/panicking.rs:72:14
  17:        0x102db74c8 - ityfuzz::evm::contract_utils::ContractLoader::from_setup::hbba6abb9156dc62f
  18:        0x102d434d0 - ityfuzz::evm::evm_main::hae69bbe4a174f0cf
  19:        0x102e14ee4 - ityfuzz::main::h5499629c420ce9f0
  20:        0x102d1ef7c - std::sys_common::backtrace::__rust_begin_short_backtrace::h3083aa1f321e3583
  21:        0x102d5dec4 - std::rt::lang_start::{{closure}}::ha81133b89b82751b
  22:        0x10413bcc4 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h61ad3d1d469c3948
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/core/src/ops/function.rs:284:13
  23:        0x10413bcc4 - std::panicking::try::do_call::hd4ce060de2afd0b8
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:552:40
  24:        0x10413bcc4 - std::panicking::try::he6d5eb62deb576b1
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:516:19
  25:        0x10413bcc4 - std::panic::catch_unwind::hd62f0e036752f2bf
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panic.rs:142:14
  26:        0x10413bcc4 - std::rt::lang_start_internal::{{closure}}::h49f798031f4167c2
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/rt.rs:148:48
  27:        0x10413bcc4 - std::panicking::try::do_call::h659daff5b9c23be4
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:552:40
  28:        0x10413bcc4 - std::panicking::try::h015f33382a2abfb5
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panicking.rs:516:19
  29:        0x10413bcc4 - std::panic::catch_unwind::h152d9e490a3adbd7
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/panic.rs:142:14
  30:        0x10413bcc4 - std::rt::lang_start_internal::hb81d8036ff3fc9c3
                               at /rustc/9d83ac217957eece2189eccf4a7232caec7232ee/library/std/src/rt.rs:148:20
  31:        0x102d5dea8 - std::rt::lang_start::hfee9562139edcc8f
  32:        0x102e15650 - _main
```

**Comment by shouc** [comment]
Seems like the deployment has reverted. 

https://github.com/fuzzland/ityfuzz/blob/master/src/evm/contract_utils.rs#L786

**Comment by shouc** [comment]
The setup file for --setup-file <SETUP FILE> requires to have a `setUp()` function to deploy and setup the project (there isn't in your case). You can add a `setUp()` function to  SimpleERC20 (example: https://github.com/maple-labs/fixed-term-loan/blob/main/tests/MapleLoan.t.sol#L27-L42). 

Another thing you can do is provide an offchain config ` --offchain-config-file <OFFCHAIN CONFIG JSON FILE>` with content like this:
```json
{
    "src/ERC20/SimpleERC20.sol": {
            "SimpleERC20": {
                 { "address": "0x.....", "constructor_args": "0x" }
            }
    }
}
```

**Comment by 0xxfu** [comment]
> The setup file for --setup-file requires to have a `setUp()` function ItyFuzz calls to deploy and setup the project (there isn't in your case). You can add a `setUp()` function for SimpleERC20 (example: https://github.com/maple-labs/fixed-term-loan/blob/main/tests/MapleLoan.t.sol#L27-L42).
> 
> In your case, you can append this to the `src/ERC20/SimpleERC20.sol` and run with `--setup-file src/ERC20/SimpleERC20.sol:SetupERC20`.
> 
> ```solidity
> ....
> contract SetupERC20 {
>       function setUp() external {
>              new SimpleERC20();
>       }
> }
> ```
> 
> Another thing you can do is provide an offchain config ` --offchain-config-file <OFFCHAIN CONFIG JSON FILE>` with content like this:
> 
> ```json
> {
>     "src/ERC20/SimpleERC20.sol": {
>             "SimpleERC20": {
>                  { "address": "0x.....", "constructor_args": "0x" }
>             }
>     }
> }
> ```

Thanks, it works for me now.

**Comment by 0xxfu** [comment]
WTF, the setup feature is so cool.
