### ISSUE TITLE
thread 'main' panicked at 'assertion failed: 4 * 8 >= slice.len()', 

### ISSUE THREAD

**Issue by rappie** [fuzzland/ityfuzz#38]
On BSC:

```
...

fetching abi 0x406ec2705f1399d25801bd86b7d8d69ab9a91ab9
constructor()
EMISSION()
LOCK()
MAX_TEAM_RATE()
PRECISION()
REBASEMAX()
TAIL_EMISSION()
WEEK()
_initialize(address[],uint256[],uint256)
_rewards_distributor()
_thena()
_ve()
_voter()
acceptTeam()
active_period()
calculate_emission()
calculate_rebate(uint256)
check()
circulating_emission()
circulating_supply()
initialize(address,address,address)
isFirstMint()
owner()
pendingTeam()
period()
renounceOwnership()
setEmission(uint256)
setRebase(uint256)
setRewardDistributor(address)
setTeam(address)
setTeamRate(uint256)
setVoter(address)
team()
teamRate()
transferOwnership(address)
update_period()
weekly()
weekly_emission()
Voted for 0
thread 'main' panicked at 'assertion failed: 4 * 8 >= slice.len()', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.12.1/src/lib.rs:38:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/core/src/panicking.rs:48:5
   3: <primitive_types::U256 as core::convert::From<&[u8]>>::from
   4: <ityfuzz::evm::oracle::IERC20OracleFlashloan as ityfuzz::oracle::Oracle<ityfuzz::evm::vm::EVMState,primitive_types::H160,revm::interpreter::bytecode::Bytecode,bytes::bytes::Bytes,primitive_types::H160,primitive_types::U256,alloc::vec::Vec<u8>,ityfuzz::evm::input::EVMInput,ityfuzz::state::FuzzState<ityfuzz::evm::input::EVMInput,ityfuzz::evm::vm::EVMState,primitive_types::H160,primitive_types::H160,alloc::vec::Vec<u8>>>>::oracle
   5: <ityfuzz::feedback::OracleFeedback<VS,Addr,Code,By,Loc,SlotTy,Out,I,S> as libafl::feedbacks::Feedback<I,S>>::is_interesting
   6: <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,I,OF,S,OT> as libafl::fuzzer::Evaluator<E,EM,I,S>>::evaluate_input_events
   7: <(Head,Tail) as libafl::stages::StagesTuple<E,EM,S,Z>>::perform_all
   8: <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,I,OF,S,OT> as libafl::fuzzer::Fuzzer<E,EM,I,S,ST>>::fuzz_loop
   9: ityfuzz::fuzzers::cmp_fuzzer::cmp_fuzzer
  10: cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by shouc** [comment]
if you are using the latest build of CLI it should work fine. Unstable Docker image may work too. I will tag a new release today.

**Comment by rappie** [comment]
Thanks. I switched to the CLI and didn't encounter any problems anymore so I guess it can be closed.

**Comment by shouc** [comment]
hey, the new stable image has been pushed. You can pull it by

```
docker pull fuzzland/ityfuzz:stable
docker run -p 8000:8000 fuzzland/ityfuzz:stable
```
