### ISSUE TITLE
thread 'main' panicked at 'failed to parse abi file: Error("expected value", line: 1, column: 1)'

### ISSUE THREAD

**Issue by rappie** [fuzzland/ityfuzz#39]
I keep getting this error. Maybe it's because of rate limiting? 

```
fetching abi from https://api.bscscan.com/api/?module=contract&action=getabi&address=0x0feadcc3824e7f3c12f40e324a60c23ca51627fc&format=json&apikey=<redacted>
thread 'main' panicked at 'failed to parse abi file: Error("expected value", line: 1, column: 1)', /home/rappie/ityfuzz.git/src/evm/contract_utils.rs:87:60
stack backtrace:
   0: rust_begin_unwind
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/result.rs:1687:5
   3: ityfuzz::evm::contract_utils::ContractLoader::parse_abi_str
   4: <ityfuzz::evm::onchain::onchain::OnChain<VS,I,S> as ityfuzz::evm::middleware::Middleware<VS,I,S>>::on_step
   5: <ityfuzz::evm::host::FuzzHost<VS,I,S> as revm::evm_impl::Host<S>>::step
   6: revm::interpreter::Interpreter::run
   7: <ityfuzz::evm::host::FuzzHost<VS,I,S> as revm::evm_impl::Host<S>>::call
   8: revm::instructions::host::call
   9: revm::interpreter::Interpreter::run
  10: ityfuzz::evm::vm::EVMExecutor<I,S,VS>::execute_from_pc
  11: <ityfuzz::evm::vm::EVMExecutor<I,S,VS> as ityfuzz::generic_vm::vm_executor::GenericVM<VS,revm::interpreter::bytecode::Bytecode,bytes::bytes::Bytes,primitive_types::H160,primitive_types::H160,primitive_types::U256,alloc::vec::Vec<u8>,I,S>>::execute
  12: <ityfuzz::executor::FuzzExecutor<VS,Addr,Code,By,Loc,SlotTy,Out,I,S,OT> as libafl::executors::Executor<EM,I,S,Z>>::run_target
  13: <(Head,Tail) as libafl::stages::StagesTuple<E,EM,S,Z>>::perform_all
  14: <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,I,OF,S,OT> as libafl::fuzzer::Fuzzer<E,EM,I,S,ST>>::fuzz_loop
  15: ityfuzz::fuzzers::evm_fuzzer::evm_fuzzer
  16: cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by rappie** [comment]
Awesome. Looks like it's working.

Can I point multiple `cli` instances running on different targets/chains to the same proxy?

**Comment by shouc** [comment]
yes

**Comment by rappie** [comment]
Thanks :slightly_smiling_face: 

No more errors, closing the issue.
