### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHexCharacter { c: '<', index: 0 }'

### ISSUE THREAD

**Issue by rappie** [fuzzland/ityfuzz#43]
Using latest compiled `cli` version with proxy & flashloan v2.

- It seems to happen at random moments during fuzzing
- Doesn't happen when I set `--onchain-block-number` to `0`
- On BSC chain

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidHexCharacter { c: '<', index: 0 }', /home/rappie/Desktop/ityfuzz.git/src/evm/onchain/endpoints.rs:557:74
stack backtrace:
   0: rust_begin_unwind
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/result.rs:1687:5
   3: ityfuzz::evm::onchain::endpoints::OnChainConfig::get_contract_slot
   4: <ityfuzz::evm::onchain::onchain::OnChain<VS,I,S> as ityfuzz::evm::middleware::Middleware<VS,I,S>>::on_step
   5: <ityfuzz::evm::host::FuzzHost<VS,I,S> as revm::evm_impl::Host<S>>::step
   6: revm::interpreter::Interpreter::run
   7: ityfuzz::evm::vm::EVMExecutor<I,S,VS>::execute_from_pc
   8: <ityfuzz::evm::vm::EVMExecutor<I,S,VS> as ityfuzz::generic_vm::vm_executor::GenericVM<VS,revm::interpreter::bytecode::Bytecode,bytes::bytes::Bytes,primitive_types::H160,primitive_types::H160,primitive_types::U256,alloc::vec::Vec<u8>,I,S>>::execute
   9: <ityfuzz::executor::FuzzExecutor<VS,Addr,Code,By,Loc,SlotTy,Out,I,S,OT> as libafl::executors::Executor<EM,I,S,Z>>::run_target
  10: <(Head,Tail) as libafl::stages::StagesTuple<E,EM,S,Z>>::perform_all
  11: <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,I,OF,S,OT> as libafl::fuzzer::Fuzzer<E,EM,I,S,ST>>::fuzz_loop
  12: ityfuzz::fuzzers::evm_fuzzer::evm_fuzzer
  13: cli::main
```

**Comment by shouc** [comment]
This is likely because you got rate limited by BSC's RPC. You can swap the RPCs to your own here: https://github.com/fuzzland/ityfuzz/blob/master/proxy/main.py#L62-L74

**Comment by shouc** [comment]
Thanks for reporting, will handle this more elegantly @stanfordreject

**Comment by stanfordreject** [comment]
feel free to use ours:
```
def get_rpc(network):
    if network == "eth":
        return "https://white-dry-replica.quiknode.pro/0864a1bd29d3befccdf5cb38a2ed100f7852ca59/"
    elif network == "bsc":
        # BSC mod to geth make it no longer possible to use debug_storageRangeAt
        # so, we use our own node that supports eth_getStorageAll
        return "https://maximum-prettiest-grass.bsc.quiknode.pro/1ef79ca3b6a4442355923ab9faa10af92c82667b/" # "http://bsc.node1.infra.fuzz.land:4949"
    elif network == "polygon":
        return "https://damp-boldest-haze.matic.quiknode.pro/d41f06b2d3b6f7a01040ec4b9170df996d711549/"
    elif network == "mumbai":
        return "https://rpc-mumbai.maticvigil.com"
    else:
        raise Exception("Unknown network")
```

**Comment by rappie** [comment]
Thanks! I will do some testing.

**Comment by rappie** [comment]
No more crash, closing issue :+1:

**Comment by rappie** [comment]
> feel free to use ours:
> 

Did you mean this for testing this particular crash or can I use these in general? (I'll only use them for ItyFuzz)

**Comment by shouc** [comment]
You can use it in general. We have enough quota
