### ISSUE TITLE
thread 'main' panicked at 'arithmetic operation overflow'

### ISSUE THREAD

**Issue by rappie** [fuzzland/ityfuzz#45]
```
thread 'main' panicked at 'arithmetic operation overflow', /home/rappie/.cargo/registry/src/index.crates.io-6f17d22bba15001f/primitive-types-0.12.1/src/lib.rs:38:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:67:14
   2: <primitive_types::U256 as core::ops::arith::Mul>::mul
   3: <ityfuzz::evm::oracles::erc20::IERC20OracleFlashloan as ityfuzz::oracle::Oracle<ityfuzz::evm::vm::EVMState,primitive_types::H160,revm::interpreter::bytecode::Bytecode,bytes::bytes::Bytes,primitive_types::H160,primitive_types::U256,alloc::vec::Vec<u8>,ityfuzz::evm::input::EVMInput,ityfuzz::state::FuzzState<ityfuzz::evm::input::EVMInput,ityfuzz::evm::vm::EVMState,primitive_types::H160,primitive_types::H160,alloc::vec::Vec<u8>>>>::oracle
   4: <ityfuzz::feedback::OracleFeedback<VS,Addr,Code,By,Loc,SlotTy,Out,I,S> as libafl::feedbacks::Feedback<I,S>>::is_interesting
   5: <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,I,OF,S,OT> as libafl::fuzzer::Evaluator<E,EM,I,S>>::evaluate_input_events
   6: <(Head,Tail) as libafl::stages::StagesTuple<E,EM,S,Z>>::perform_all
   7: <(Head,Tail) as libafl::stages::StagesTuple<E,EM,S,Z>>::perform_all
   8: <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,I,OF,S,OT> as libafl::fuzzer::Fuzzer<E,EM,I,S,ST>>::fuzz_loop
   9: ityfuzz::fuzzers::evm_fuzzer::evm_fuzzer
  10: cli::main
```

**Comment by shouc** [comment]
Would you mind sharing the input?

**Comment by rappie** [comment]
```../cli -o --onchain-block-number 0 --chain-type ETH --onchain-local-proxy-addr http://127.0.0.1:5003 --panic-on-bug --flashloan --ierc20-oracle --pair-oracle --target 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D,0x35609dc59e15d03c5c865507e1348fa5abb319a8```
