### ISSUE TITLE
Still getting `Invalid chain type` with latest docker image

### ISSUE THREAD

**Issue by rappie** [fuzzland/ityfuzz#46]
Chain type: ETH

Started docker image using:
```shell
docker pull fuzzland/ityfuzz:stable
docker run -p 8000:8000 fuzzland/ityfuzz:stable
```

```
thread 'main' panicked at 'Invalid chain type', src/main.rs:170:57
stack backtrace:
   0: rust_begin_unwind
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/option.rs:2025:5
   5: cli::main
```

**Comment by shouc** [comment]
fixed, thanks. new docker img pushed
