### ISSUE TITLE
thread 'main' panicked at 'range end index 36 out of range for slice of length 4'

### ISSUE THREAD

**Issue by rappie** [fuzzland/ityfuzz#52]
```shell
./cli -o --onchain-block-number 0 --chain-type ETH --onchain-local-proxy-addr http://127.0.0.1:5003 --panic-on-bug --flashloan --concolic --ierc20-oracle --pair-oracle --target 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D,0x3c4fe0db16c9b521480c43856ba3196a9fa50e08
```

```
thread 'main' panicked at 'range end index 36 out of range for slice of length 4', /home/rappie/Desktop/ityfuzz.git/src/evm/onchain/flashloan.rs:510:53
stack backtrace:
   0: rust_begin_unwind
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:67:14
   2: core::slice::index::slice_end_index_len_fail_rt
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/slice/index.rs:78:5
   3: core::slice::index::slice_end_index_len_fail
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/slice/index.rs:70:9
   4: <ityfuzz::evm::host::FuzzHost<VS,I,S> as revm::evm_impl::Host<S>>::step
   5: revm::interpreter::Interpreter::run
   6: ityfuzz::evm::vm::EVMExecutor<I,S,VS>::execute_from_pc
   7: <ityfuzz::evm::vm::EVMExecutor<I,S,VS> as ityfuzz::generic_vm::vm_executor::GenericVM<VS,revm::interpreter::bytecode::Bytecode,bytes::bytes::Bytes,primitive_types::H160,primitive_types::H160,primitive_types::U256,alloc::vec::Vec<u8>,I,S>>::execute
   8: <ityfuzz::executor::FuzzExecutor<VS,Addr,Code,By,Loc,SlotTy,Out,I,S,OT> as libafl::executors::Executor<EM,I,S,Z>>::run_target
   9: <(Head,Tail) as libafl::stages::StagesTuple<E,EM,S,Z>>::perform_all
  10: <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,I,OF,S,OT> as libafl::fuzzer::Fuzzer<E,EM,I,S,ST>>::fuzz_loop
  11: ityfuzz::fuzzers::evm_fuzzer::evm_fuzzer
  12: cli::main
```

**Comment by iVoider** [comment]
`cli -c ETH --onchain --onchain-block-number 0 -f -p -i --flashloan-price-oracle onchain --target 0x1DfF114dfBBcaedcA5f0d46DC8e9615dfC2645bd,0xe761bf731a06fe8259fee05897b2687d56933110,0x7E30fC3411AFD4c0381a4ec6e6ba09e19B9EDb5B,0xE1F27adD45652812BAD02E26EEc588F0EF97e1d3,0xA840C73a004026710471F727252a9a2800a5197F,0xBeA839F978c1C398B0303C00898a5130C9506401,0xf591D878608e2e5c7D4f1E499330f4AB9BbaE37a,0x1D28D426e4e20B9d43130C23252b8eD6F9cB388E,0x46f992D00C2Dfb6FbbbB64d69Ab353c2fC435ACE,0x8412d4C04f79b8886cE0bfdF38Baf7Af13011eee,0x3f950f06064A43d42a8e7C199BB77b8E3A4b2096,0x78537a6CeBa16f412E123a90472C6E0e9A8F1132,0xA7AA5BE408B817A516b40Daea7a919664f13f193,0x7A172816C0560964E6aD54EF54AFABB035614047,0x61134511187a9a2DF38D10DBe07Ba2e8E5563967,0x211C74DB951c161c5A379363716EbDca5125EF59,0x93Dede06AE3B5590aF1d4c111BC54C3f717E4b35,0x9825F776908fF9815E284351D1Fe94fE75F15B49,0x76a50ba7b751409fc5CE39eA9818EC4e723ad173,0xBC11De1F20e83F0a6889B8c7A7868E722694E315,0x7879A9c464af7805712404Cf4A8366c475034F91,0xcE4a49d7ed99C7c8746B713EE2f0C9aA631688d8,0xF65a1E41d0491621596D4B61B85e73E38Cf7e424,0xEFc8a5A82D09D1068d26Ad57E2F57c0037C4f20f,0xA22a7ec2d82A471B1DAcC4B37345Cf428E76D67A,0xA3dfCcbad1333DC69997Da28C961FF8B2879e653,0x03323143a5f0D0679026C2a9fB6b0391e4D64811,0x0256fc7ba8d1513be9661c504f36e075942d9a49,0x9735f7d3ea56b454b24ffd74c58e9bd85cfad31b,0x49930AD9eBbbc0EB120CCF1a318c3aE5Bb24Df55,0x6b6BD434A822AE51704aeD4436DaC62A0772166C,0xdd8AC2d5A739Bb4a591C5b0c7e613B810fE83fF1,0x5951f159eF502f0571A5D7e136a580DcadEa42Eb,0xfC30820ba6d045b95D13a5B8dF4fB0E6B5bdF5b9,0x062Bf725dC4cDF947aa79Ca2aaCCD4F385b13b5c,0x1EEd2DbeB9fc23Ab483F447F38F289cA15f79Bac,0x5C6374a2ac4EBC38DeA0Fc1F8716e5Ea1AdD94dd,0x35b2c16de6F283Ab0949964d90cCf930f378ade6,0x4ac2377ed3ee376Ff07d706BEaBC2Fa38ecfB41C,0xe3cfdbfa339b749c6df27854e11df3398b12d56e,0xbc2FB245594a68c927C930FBE2d00680A8C90B9e`

Btw, #136 also affects these ones.
