### ISSUE TITLE
Panic for Fuzzing on Ethereum in Docker Image

### ISSUE THREAD

**Issue by g0rk** [fuzzland/ityfuzz#6]
```
thread 'main' panicked at 'Invalid chain type', src/main.rs:135:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/432abd86f231c908f6df3cdd779e83f35084be90/library/core/src/option.rs:1880:5
   5: cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by g0rk** [comment]
Running on fuzzland/ityfuzz with (ETH, 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2, 17080000)
