### ISSUE TITLE
Proxy error: Exception on /swap_path/eth/.../latest

### ISSUE THREAD

**Issue by rappie** [fuzzland/ityfuzz#64]
Let me know if you need more info

```[2023-05-15 12:36:01,204] ERROR in app: Exception on /swap_path/eth/0x27a94869341838d5783368a8503fda5fbcd7987c/latest [GET]
Traceback (most recent call last):
  File "/home/rappie/.pyenv/versions/ityfuzz/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rappie/.pyenv/versions/ityfuzz/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/rappie/.pyenv/versions/ityfuzz/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rappie/.pyenv/versions/ityfuzz/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/rappie/Desktop/ityfuzz.git/proxy/main.py", line 621, in swap_path
    return flask.jsonify(find_path_subgraph(network, token_address.lower(), block))
  File "/home/rappie/Desktop/ityfuzz.git/proxy/main.py", line 371, in find_path_subgraph
    hops = get_all_hops(token, network, block, known=set())
  File "/home/rappie/Desktop/ityfuzz.git/proxy/main.py", line 322, in get_all_hops
    hops[token] = get_pair(token, network, block)
  File "/home/rappie/.pyenv/versions/ityfuzz/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/rappie/.pyenv/versions/ityfuzz/lib/python3.10/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/home/rappie/.pyenv/versions/ityfuzz/lib/python3.10/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/home/rappie/Desktop/ityfuzz.git/proxy/main.py", line 266, in get_pair
    res = res["data"]
KeyError: 'data'
```

**Comment by rappie** [comment]
Any idea with this one? Is this something I could hotfix locally?

**Comment by ByteSecurity** [comment]
Could you send me the URL requested on the traceback above?  I would like to try reproducing it.

My guess is that either:

1. TheGraph has stopped serving your IP.
2. This trading pair is not indexed on TheGraph.

**Comment by rappie** [comment]
```
url https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2
error {'errors': [{'message': 'Failed to decode `block.number` value: `subgraph QmWTrJJ9W8h3JE19FhCzzPYsJ2tgXZCdUqnbyuo64ToTBN has only indexed up to block number 17308397 and data for block number 17485440 is therefore not yet available`'}]}
```

It seems to be because thegraph is not indexing fast enough. Is nobody else encountering this?

I've been using a bigger delay as a workaround:
```python
    if network == "eth":
        # delay = 50
        delay = 200000
    elif network == "bsc":
        delay = 700000
    else:
        delay = 50

    block_int = int(block, 16) if block != "latest" else int(get_latest_block(network), 16) - delay

```

**Comment by ByteSecurity** [comment]
Please send me your "/swap_path/<network>/<token_address>/<block>", I'll try

_Network latency is also one of the reasons why data is not available_

**Comment by ByteSecurity** [comment]
`has only indexed up to block number 17308397 and data for block number 17485440 is therefore not yet available`
I have also encountered this issue. It is likely that TheGraph's index is not up to date. If it is not necessary to use the latest block, I choose to use the block number returned by TheGraph.

**Comment by rappie** [comment]
`/swap_path/eth/0x64aa3364f17a4d01c6f1751fd97c2bd3d7e7f1d5/latest`

**Comment by ByteSecurity** [comment]
> `/swap_path/eth/0x64aa3364f17a4d01c6f1751fd97c2bd3d7e7f1d5/latest`

I know where the problem is now. It's because TheGraph's block synchronization time is three years ago, which makes it impossible to get data with the latest blocks.

https://thegraph.com/hosted-service/subgraph/uniswap/uniswap-v2

**Comment by ByteSecurity** [comment]
Added a fallback to use the old block method for requesting, as well as error handling.
