### ISSUE TITLE
time overflow

### ISSUE THREAD

**Issue by Mixy1** [fuzzland/ityfuzz#66]
Environment:

Docker 
fuzzland/ityfuzz:latest 9443aba6458d
on wsl

Have ran multiple smart contracts and all of them seem to crash at around 7 minutes with the following error:
```
thread 'main' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:31
stack backtrace:
   0: rust_begin_unwind
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/option.rs:2025:5
   5: core::option::Option<T>::expect
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/option.rs:913:21
   6: <core::time::Duration as core::ops::arith::Sub>::sub
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/time.rs:936:31
   7: <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,I,OF,S,OT> as libafl::fuzzer::Fuzzer<E,EM,I,S,ST>>::fuzz_loop
   8: ityfuzz::fuzzers::evm_fuzzer::evm_fuzzer
   9: cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by shouc** [comment]
Is NTP enabled? It seems Windows sometimes throw time backward

**Comment by Mixy1** [comment]
hmm it seems like this might be due to the wsl clock skew issues. Trying a hwclock sync now.

**Comment by shouc** [comment]
This can't be fixed here. seems to be an internal issue @ https://github.com/aflplusplus/libafl
