### ISSUE TITLE
Panic When Fuzzing Contracts with DELETGATECALL

### ISSUE THREAD

**Issue by g0rk** [fuzzland/ityfuzz#8]
```
thread 'main' panicked at 'already borrowed: BorrowMutError', /root/fuzzing/ityfuzz/src/evm/onchain/flashloan.rs:232:60
stack backtrace:
   0: rust_begin_unwind
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/af06dce64bf87ea9206bdf6cff61c144b9ce8458/library/core/src/result.rs:1687:5
   3: ityfuzz::evm::onchain::flashloan::Flashloan<VS,I,S>::on_contract_insertion
   4: <ityfuzz::evm::onchain::onchain::OnChain<VS,I,S> as ityfuzz::evm::middleware::Middleware<VS,I,S>>::on_step
   5: <ityfuzz::evm::host::FuzzHost<VS,I,S> as revm::evm_impl::Host<S>>::step
   6: revm::interpreter::Interpreter::run
   7: <ityfuzz::evm::vm::EVMExecutor<I,S,VS> as ityfuzz::generic_vm::vm_executor::GenericVM<VS,revm::interpreter::bytecode::Bytecode,bytes::bytes::Bytes,primitive_types::H160,primitive_types::H160,primitive_types::U256,alloc::vec::Vec<u8>,I,S>>::fast_static_call
   8: <ityfuzz::evm::oracle::IERC20OracleFlashloan as ityfuzz::oracle::Oracle<ityfuzz::evm::vm::EVMState,primitive_types::H160,revm::interpreter::bytecode::Bytecode,bytes::bytes::Bytes,primitive_types::H160,primitive_types::U256,alloc::vec::Vec<u8>,ityfuzz::evm::input::EVMInput,ityfuzz::state::FuzzState<ityfuzz::evm::input::EVMInput,ityfuzz::evm::vm::EVMState,primitive_types::H160,primitive_types::H160,alloc::vec::Vec<u8>>>>::oracle
   9: <ityfuzz::feedback::OracleFeedback<VS,Addr,Code,By,Loc,SlotTy,Out,I,S> as libafl::feedbacks::Feedback<I,S>>::is_interesting
  10: <ityfuzz::fuzzer::ItyFuzzer<VS,Loc,Addr,Out,CS,IS,F,IF,I,OF,S,OT> as libafl::fuzzer::Evaluator<E,EM,I,S>>::evaluate_input_events
  11: ityfuzz::fuzzers::evm_fuzzer::evm_fuzzer
  12: cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by shouc** [comment]
shall be fixed in #9
